services:
  app:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports: 
      - 127.0.0.1:1433:1433
    #build: .
    volumes:
      - .:/app
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SQLMonitor2019
    container_name: SQL_Monitor_2019-latest
    #command:
    working_dir: /usr/config